### PR TITLE
fixed "ValueError: matrix G is not positive definite"

### PR DESCRIPTION
**Pull request by DonatoMeoli**
As suggested by @andreamad8 [here](https://github.com/facebookresearch/GradientEpisodicMemory/issues/2).

### CODE REVIEW

**Comment by stephane-caron** [comment]
Many solvers won't accept non-definite cost matrices (note that in some cases there is no unique optimum if `P` is not definite). The fact that they complain with an exception is actually desired here: making a non-definite matrix definite by adding epsilons to the diagonal is fine, but users should do it on their side as the value of epsilon will depend on their problem (for instance, in your proposal you chose `epsilon=1e-3`, but this won't do if most non-zero values in a user's `P` matrix are around `1e-5`).

**Comment by DonatoMeoli** [comment]
What do you think if (just for the solvers that don't accept indefinite cost matrices) we add some lines of code before calling the real solver to evaluate the eps value of the most non-zero values in the user's P matrix and then we add this eps to the diagonal as I have already done? It could be a valid way to avoid raising the exception.

**Comment by stephane-caron** [comment]
The complexity hides behind the operation:

> evaluate the eps value of the most non-zero values in the user's P matrix

Ideally, we would like a value of epsilon that does not change the optimum of the problem. To do this, we should do an [eigendecomposition](https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix) of the P matrix and make sure that epsilon is smaller than the lowest eigenvalue of P. Unfortunately, doing an eigendecomposition can take as much time as solving the QP itself.

Yet, let us even assume that we have an eigendecomposition of P. The thing is, our current problem is rooted in the [condition number](https://en.wikipedia.org/wiki/Conditioning_number) of P. Here is a minimal example:

```python
from qpsolvers import solve_qp
from numpy import array, zeros
eps = 1e-21
P = array([
    [1. + eps, 0., 0.3],
    [0., 0.1 + eps, 0.],
    [0., 0., 1e-20 + eps]])
q = zeros(3)
```
```python
>>> x = solve_qp(P, q, solver="quadprog")
ValueError: matrix G is not positive definite
```

Here the lowest eigenvalue of ``P`` is ``1e-20``, which raises it's condition number to ``1e+20``. A high condition number yields numerical instability. Even if we had ``eps=1e-21`` to the diagonal of the matrix, the solver will still believe it is not positive definite because this ``eps`` will vanish in floating-point operations that involve numbers much bigger than it.

**Comment by stephane-caron** [comment]
Investigating this, I found that some solvers provide more warnings than others on ill-conditioned matrices. Here is another example:
```python
from qpsolvers import solve_qp
from numpy import array, zeros
eps = 1e-21
P = array([
    [1. + eps, 0., 0.3],
    [0., 0.1 + eps, 0.],
    [0., 0., 1e-20 + eps]])
q = zeros(3)
G = array([[1., 2., 1.], [2., 0., 1.], [-1., 2., -1.]])
h = array([3., 2., -2.]).reshape((3,))
A = array([1., 1., 1.])
b = array([1.])
for solver in qpsolvers.available_solvers:
    print("{}: {}".format(solver, solve_qp(P, q, G, h, A, b, solver=solver)))
```
This yields:
- cvxopt: ``[-1.22192142e-09 -3.33333865e-01  1.33333387e+00]``
- qpoases: ``[ 0.53839286 -0.33333333  0.79494048]``

We see how for the second coordinate the two solvers get the same answer, while returning something completely different for the two others. The cause of the problem here is that the QP is ill-defined.These two solvers are only to blame because they don't warn the user that their P matrix is ill-conditioned :wink:

Some other solvers raise exceptions when they detect this:
- quadprog: ``ValueError: matrix G is not positive definite``
- ecos: ``DCPError: Problem does not follow DCP rules.``

And finally, OSQP opted for a "throwing a grenade at you" kind of warning:
- osqp: ``[nan nan nan]``

**Pull request closed without merging**
