### PR TITLE
added bound constraints support and updated README.md

### PR DESCRIPTION
**Pull request by dmeoli**
Since a constrained quadratic function is defined by linear equality, inequality and bound or box constraints in its standard form, I added the latter trough `lb` and `ub` parameters in `solve_qp` method.

Below the code used to generate the updated latex equation in the readme through https://www.codecogs.com/latex/eqneditor.php:

```
\begin{equation}
\begin{aligned}
{\color{Black} \min_x \quad} & {\color{Black} \frac{1}{2}x^T P x + q^T x} \\
{\color{Black} \textrm{subject to} \quad} & {\color{Black} lb \leq x \leq ub} \\ & {\color{Black} Gx \leq h} \\ & {\color{Black} Ax = b}
\end{aligned}
\end{equation}
```

Also my IDE corrected some indentations according to the PEP8 standard.

### CODE REVIEW

**Comment by stephane-caron** [comment]
Great contribution!

I'm curious why you switched from ``concatenate`` to ``h/vstack``? I checked locally and the former is slightly faster.

**Comment by dmeoli** [comment]
Oh yes? I won't explain it! According to numpy source code `v/hstack` are wrappers for the more generic `concatenate` method.
I changed it just for an intuitive reason but if you prefer I can rollback to `concatenate`!

**Comment by dmeoli** [comment]
Thx for merging @stephane-caron. Can you again update the PyPI version? 
I'm sorry for the trouble 😂

**Comment by stephane-caron** [comment]
No worries, thank you for this contribution!

You can update from PyPI to v1.3 :wink:

**Pull request merged**
